### ISSUE TITLE
Where can i get your paper

### ISSUE THREAD

**Issue by changruowang** [sebcolla/Simulation-Tool-TFE-OMAS#1]
Hello, i am intresed in your code ,i want to get the orignal paper for learning, can you provide? thank you!

**Comment by sebcolla** [comment]
Hello,
I can commit a pdf of my master thesis into this repository.
The official online version will be available soon.

What are you working on?

Regards

**Comment by sebcolla** [comment]
I have added a link to the full text in the readme but it does not work yet since the text is not yet released by the institution. Sorry for this. I think it should work in the next few days.
I will close this issue when the link is active.
